### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VirtualPedestrian** [EmiyaSyahriel/CrossLauncher#1]
Sorry if I am disturbing you but can you give me the apk for this because I'm not skilled enough to compile an app btw can you make a option to switch to PSP XMB rather than PS3 XMB

**Comment by VirtualPedestrian** [comment]
Oops I'm sorry I'm a idiot I just realized there's a release apk

**Comment by EmiyaSyahriel** [comment]
Well, if you can provide me with one picture (or screenshot) of the authentic PSP XMB (no theme, just default XMB). I probably can do something with it. I never had a PSP before, just a PS3, so my reference is just PS3 currently.

**Comment by VirtualPedestrian** [comment]
I don't have a PSP but it look pretty much the same with PS3 just remove this bar 
![Screenshot_20201128-133659](https://user-images.githubusercontent.com/73787177/100495176-b873b680-3183-11eb-987d-f9d9393fe077.png) and btw can you turn off the transparent background so my wallpaper doesn't look dark

**Comment by EmiyaSyahriel** [comment]
Here, I added your requested features: Custom background color, adjustable clock bar : [Alpha 4](
https://github.com/EmiyaSyahriel/CrossLauncher/releases/tag/alpha_4)

The FPS box shouldn't appear unless the debug setting for FPS is enabled,

P.S : Sorry, I just carried away by the label settings

**Comment by EmiyaSyahriel** [comment]
Anyway, the compilation of this project should be simple and straighforward. 
1. Pull this project source code from git (or download it as ZIP then extract it)
2. Open your local repo (or extracts) from Android Studio as an Android Project.
3. Wait until gradle finished resolving and caching all needed dependencies. 
4. Deploy to your device (The play button at top right)

Custom background color can be found at the Setting category, to set it clear / transparent, Put "#00FFFFFF" to the dialog box. It requires Hex color in format "#aarrggbb" where you can control the color transparency by modifying the first 2 digit (the "aa")

**Comment by VirtualPedestrian** [comment]
Forget to mention that the app setting reset itself after not being used
![Screenshot_20201129-134127](https://user-images.githubusercontent.com/73787177/100534472-2387c080-324a-11eb-84a7-ac958330e03e.jpg)
![Screenshot_20201129-133952](https://user-images.githubusercontent.com/73787177/100534474-27b3de00-324a-11eb-8b8a-f4c06f25ba2f.jpg)

**Comment by EmiyaSyahriel** [comment]
Please open another Issue since it was different bug 🙂. 

Well, new bugs keep appearing since I reworked on how item icon and text is accessed before rendered.
