### ISSUE TITLE
Custom Aspect Ratio & Game List Filtering

### ISSUE THREAD

**Issue by N3kowarriorCZenchilada** [EmiyaSyahriel/CrossLauncher#27]
19:9 aspect ratio support? And AetherSX2 not recognized as emulator (not added to game section)

**Comment by EmiyaSyahriel** [comment]
I'm working on adding "custom aspect ratio" option to the reference resolution menu so every aspect ratio can be covered including the obscure ones like 8:3 or 5:1, possibly in the next release.

As for AetherSX2, the developer seems to not set the `isGame=true`  or `appCategory=game` in their app manifest, therefore is not added to the game section. The implementation to "filter app by package name to be added to the game section" is already in the app actually, I haven't implement the entry to it yet.

**Comment by N3kowarriorCZenchilada** [comment]
Thank you new version gonna be lit

**Comment by EmiyaSyahriel** [comment]
These features has been implemented in several version of Action Build, can you check it? [Action Build](https://github.com/EmiyaSyahriel/CrossLauncher/actions)

**Comment by EmiyaSyahriel** [comment]
Now also available in the [Alpha 20240226](https://github.com/EmiyaSyahriel/CrossLauncher/releases/tag/a_20240226) release. 

In case there is no feedback until March 29th , I'll consider this feature is done and close this issue

**Comment by EmiyaSyahriel** [comment]
No additional feedback, considering request done. Now closing ...
