### ISSUE TITLE
[FEATURE REQUEST] Add white background for all icons

### ISSUE THREAD

**Issue by xmha97** [EmiyaSyahriel/CrossLauncher#34]
Hi, please add the white background for all icons.
Some icons are transparent and it's bad. (unadoptive icons)

![Screenshot_2023-04-02-20-45-39-154_id.psw.vshlauncher.jpg](https://user-images.githubusercontent.com/23485114/229368737-60d3401c-605d-486f-b778-e5899ee83a31.jpg)

**Comment by EmiyaSyahriel** [comment]
Implemented, please check [this release](https://github.com/EmiyaSyahriel/CrossLauncher/releases/tag/a_20230528) if this suit your feature request.

You can enable it at `Settings > System > Legacy Icon Background`. You can also change the color of the icon background, if you want.

**Comment by EmiyaSyahriel** [comment]
Hello, Seems like there is no feedback from you in a month, In case you didn't give anymore feedback until 30 July, I'll close this issue.

**Comment by EmiyaSyahriel** [comment]
No feedback after a certain time, Closing the issue.
