### ISSUE TITLE
When changing an app's category, it does not change. (Kind of)

### ISSUE THREAD

**Issue by AkiraKusanagi** [EmiyaSyahriel/CrossLauncher#39]
I was checking out features and noticed that you can change the category of an app. I tried it out on two apps. (FNAF 2 and SFIV CE, which are games but for some reason were in the Apps category.) I changed the category of both to Games. Then restarted the launcher. FNAF 2 was then in the Games category, but SFIV was still in the Apps category.

**Comment by EmperorJk13** [comment]
This is a really dumb question. Can I set the status bar clock to the 12 hour format instead of 24?

**Comment by EmiyaSyahriel** [comment]
I can't found the code for the actual category change yet, The "Category" field is just there for future implementation, You can check the code for this [here](https://github.com/EmiyaSyahriel/CrossLauncher/blob/718f0b1e91050abf81e1fdc76e574d83d4c84675/launcher_app/src/main/java/id/psw/vshlauncher/VSH.AppListing.kt#L91) and [here](https://github.com/EmiyaSyahriel/CrossLauncher/blob/718f0b1e91050abf81e1fdc76e574d83d4c84675/launcher_app/src/main/java/id/psw/vshlauncher/VSH.AppListing.kt#L11) (The code should be easy enough to understand).

About the Status bar format, you can change it via `Settings > Display Settings > Status Bar Text Format`. The dialog is not that good yet, you can swipe left and right to choose between Edit and Save, and you can see all `{sdf:[format]}` format reference [here](https://developer.android.com/reference/android/icu/text/SimpleDateFormat). In your case, It should be only `{sdf:dd/M HH:mm}` (you should omit the `a` from there to remove the `AM/PM` text).

**Comment by AkiraKusanagi** [comment]
Was fixed in an Action Build.
