### ISSUE TITLE
Make it so that holding the D-Pad continuously scrolls in the launcher

### ISSUE THREAD

**Issue by AkiraKusanagi** [EmiyaSyahriel/CrossLauncher#41]
I prefer to use the D-Pad in menus, whether in-game or something else. So when I tried using the D-Pad on the launcher it seemed fine, but when I held down on the D-Pad in a certain direction, it only moves on the launcher as if I've just pressed the button, not held it. When I test the analog stick out, it works flawlessly. Think you could make this work? Thanks.

**Comment by EmperorJk13** [comment]
Sorry, dumb post.

**Comment by EmiyaSyahriel** [comment]
Project Card Added : [Input Abstraction](https://github.com/EmiyaSyahriel/CrossLauncher/projects/1#card-59801858)

**Comment by AkiraKusanagi** [comment]
Was implemented in an Action Build.
