### ISSUE TITLE
4:3 Support?

### ISSUE THREAD

**Issue by chronozero45** [EmiyaSyahriel/CrossLauncher#6]
Hi, I used this launcher for my Retroid Pocket 2 (an android gaming device with a 4:3 screen/aspect ratio) and whenever I use the CrossLauncher on it, things like the startup screen, menus, and clock bar don't fit on the screen and incorrectly stretch beyond it, making them not fully visible. Any help here or fix for this would be appreciated.

![20210520_142013](https://user-images.githubusercontent.com/84542463/119044234-2badf680-b977-11eb-8781-60996a4a49df.jpg)
![20210520_142050](https://user-images.githubusercontent.com/84542463/119044261-37012200-b977-11eb-93d4-5cea31302f5b.jpg)
![20210520_142137](https://user-images.githubusercontent.com/84542463/119044316-497b5b80-b977-11eb-90d2-3f41724a0c24.jpg)
![20210520_142148](https://user-images.githubusercontent.com/84542463/119044381-5b5cfe80-b977-11eb-9e8e-f15db332565f.jpg)

**Comment by VirtualPedestrian** [comment]
Try changing display size in Android's settings

**Comment by VirtualPedestrian** [comment]
My phone have the same problem too btw [
![Screenshot_20210521-233811](https://user-images.githubusercontent.com/73787177/119163382-f0eab200-ba8d-11eb-9be2-f6dbcbdf1d10.jpg)
](url)

**Comment by EmiyaSyahriel** [comment]
The rendering code in the compiled APK is actually still hard-coded to respect device scaling setting and device system bars, Even it is like that too on my BlueStack emulator 😞. I don't know that the cutting will look so bad in a 4:3 device.

I cannot really promise when can I fix it as I have to re-make almost the entire thing and my office is still coming even though I said that I will be free at February, Even I still haven't fixed the other issue on this project for real.

And... AFAIK you cannot change Android device from the device itself unless the ROM supported it from factory or is rooted, I usually use `adb` that comes with Android SDK to do it, you can download it separately though.

BTW, I don't know if it would looks very good on a retroid device 😋

**Comment by EmiyaSyahriel** [comment]
![Screenshot_20210608-084645.png](https://user-images.githubusercontent.com/24495564/121109652-2f29f480-c836-11eb-9989-4ed879d87ea2.png)

So far this is what I got, the rendering size is now based on reference size scaling, so it can be resized accordingly by user regardless of the device hardware and settings. It was just the rendering though, the main function is still not done yet.

**Comment by EmiyaSyahriel** [comment]
It should've been fixed by this [release (alpha 20221205_A0139)](https://github.com/EmiyaSyahriel/CrossLauncher/releases/tag/a_20221205). It's still 16:9 fitted to 4:3 tho, I still haven't made the reference size accessible from the launcher's settings.

It's been half a year huh...

**Comment by EmiyaSyahriel** [comment]
Custom Reference Resolution is now available in [release of Alpha 20230129_0235P](https://github.com/EmiyaSyahriel/CrossLauncher/releases/tag/a_20230129). You now can use any resolution (as long as it's near 1280 or 720) in any aspect ratio, the renderer will adjust it's scale accordingly. 

If it's fixed this issue, then please close this issue, or please give feedback if this issue is still remains. If no initial feedback before Feb 28, I'll consider this issue is finished and can be closed.

**Comment by chronozero45** [comment]
Hi! Sorry for responding so late, it’s been a really long time, I forgot about this thread. Anyways, I ended up using the version I had and stopped minding the weird cropped visuals since the newer versions of the XMB launchers unfortunately lagged heavily, ran slowly and didn’t look very good on my Retroid Pocket 2, whereas the old version ran perfectly fine despite the cropping. But thanks either way, because even if the newer versions don’t work on my device, I’m sure others with different devices will enjoy it. Either way, I’ve bought a Retroid Pocket 3+ recently which is 16;9 and might work perfectly fine with this launcher moving foward. Thanks for the
