### ISSUE TITLE
First run message appearing every time i launch the app

### ISSUE THREAD

**Issue by PSPhoneLemming** [EmiyaSyahriel/CrossLauncher#7]
(I just made a account for this, i know nothing about developing and scripting stuff)

Whenever i open the app (either standalone or set as default homescreen ui) I get the First Run message appearing everytime, i checked everywhere in the launcher to disable this, and it seems that theres no option for that, can you add a "Dont show again." thing? that would be helpful..

Sincerely,

A desperate lemming who wants his 2017 phone be a gaming console..

**Comment by EmiyaSyahriel** [comment]
It's been opened as issue #2 though. That's because I forgot to program the state saving, which should keep the dialog from appearing after the app first run. 

It's been almost a year since the last release as I currently doing a lot of changes in the app code.

**Comment by PSPhoneLemming** [comment]
Ah, i am fine with waiting, take your time.
