### ISSUE TITLE
[Feature Request] [Touchscreen optimization] Add arrows to Fly out menu

### ISSUE THREAD

**Issue by EmiyaSyahriel** [EmiyaSyahriel/CrossLauncher#93]
### Discussed in https://github.com/EmiyaSyahriel/CrossLauncher/discussions/90

<div type='discussions-op-text'>

<sup>Originally posted by **glitch128** May 10, 2024</sup>
so, it is kinda difficult to figure out how the flyout menu works with touchscreen. for example, the app flyout menu with [Switch Sort, Launch, App Info, Create Customization Dir, ect.]. adding arrows in the blank spaces could help tell the user how it works and how to navigate that menu.
ex:
```
      ^

Switch Sort
...
Uninstall

      v
```</div>

**Comment by EmiyaSyahriel** [comment]
@glitch128 I have implemented it in [this](https://github.com/EmiyaSyahriel/CrossLauncher/actions/runs/9752125629) build, can you try it?

I also added the options to change the side menu navigation on `Settings > System Settings > Side Menu Touch Navigation Mode` (Still `Tap` by default), because the current tapping navigation is very disjointed from how other UI component is navigated. And since the side menu code is now untangled from other system code, I can easily add this system without making the code unreadable.

**Comment by glitch128** [comment]
that seems good. it adds better indication of how to use it with a touchscreen
